all:
	$(MAKE) -C src
	$(MAKE) -C find-superstring
	$(MAKE) -C verify-superstring
	$(MAKE) -C verification

clean:
	$(MAKE) -C src clean
	$(MAKE) -C find-superstring clean
	$(MAKE) -C verify-superstring clean
	$(MAKE) -C verification clean
