all:
	$(MAKE) -C src
	$(MAKE) -C find-superstring
	$(MAKE) -C gen-repetitive
	$(MAKE) -C verify-superstring

clean:
	$(MAKE) -C src clean
	$(MAKE) -C find-superstring clean
	$(MAKE) -C gen-repetitive clean
	$(MAKE) -C verify-superstring clean
